### ISSUE TITLE
What license is this shared under?

### ISSUE THREAD

**Issue by ZmeiGorynych** [rahulnyk/research_agent#1]
Hi! 
Thanks a lot for open sourcing this!
We would like to use some of the code here (mostly some of the prompts) in our own project, and it would be great to have clarity, on what terms you are sharing it. Is it under the MIT license, like LllamaIndex and Langchain, for example? 
Could you possibly add a LICENSE file to this repo to clarify?
Thanks a lot!

**Comment by rahulnyk** [comment]
Hey Egor
Added MIT License to the repo. 
Thanks

**Comment by ZmeiGorynych** [comment]
Thanks a lot!
We'll have a go at recasting your approach using a knowledge graph for intermediate data representation, will let you know how it goes ;)

**Comment by ZmeiGorynych** [comment]
[Here](https://motleycrew.readthedocs.io/en/latest/examples/research_agent.html)'s our knowledge-graph based take on it ;)
